platform :ios, '11.0'
use_frameworks!

target 'MovieDB' do
    pod 'SnapKit', '~> 4.0.0'
    pod 'SDWebImage', '~> 4.0'
    pod 'lottie-ios', '~> 2.5.0'
end

target 'MovieDBTests' do
    pod 'lottie-ios', '~> 2.5.0'
end

swift_4_1_pod_targets = ['SnapKit']

post_install do | installer |
    installer.pods_project.targets.each do |target|
        if swift_4_1_pod_targets.include?(target.name)
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.1'
            end
        end
    end
end
